---
Name: graphqldemoroutes
---
SilverStripe\Control\Director:
  rules:
    'test': 'Blueo\GraphQLDemo\GraphQLDemoController'
    # graphql:
    #   Controller: 'Blueo\GraphQLDemo\EndpointController'
    #   Stage: Stage
